# Generated by Django 4.2.7 on 2023-11-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('REMOTE', 'REMOTE'), ('ON_SITE', 'ON_SITE')], max_length=50)),
                ('job_location', models.CharField(max_length=150)),
                ('job_category', models.CharField(max_length=50)),
                ('application_deadline', models.CharField(max_length=150)),
                ('job_description', models.TextField()),
                ('upload_logo', models.ImageField(upload_to='uploaded_logo')),
                ('company_name', models.CharField(max_length=50)),
                ('company_description', models.TextField()),
                ('how_to_apply', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
