# Generated by Django 4.2.7 on 2024-02-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_crud', '0001_initial'),
        ('company_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('REMOTE', 'REMOTE'), ('ON_SITE', 'ON_SITE')], max_length=50)),
                ('job_location', models.CharField(max_length=150)),
                ('application_deadline', models.CharField(max_length=150)),
                ('job_description', models.TextField()),
                ('how_to_apply', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.company')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_crud.category')),
            ],
        ),
    ]
